-- MySQL Script generated by MySQL Workbench
-- Fri Nov  3 11:40:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema auditoria10
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auditoria10
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auditoria10` DEFAULT CHARACTER SET utf8 ;
USE `auditoria10` ;

-- -----------------------------------------------------
-- Table `auditoria10`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria10`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT '1',
  `token` VARCHAR(100) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `role` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auditoria10`.`business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria10`.`business` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `logo` VARCHAR(100) NOT NULL DEFAULT 'business_default.png',
  `folio` VARCHAR(100) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auditoria10`.`users_has_business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria10`.`users_has_business` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `business_id` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  INDEX `fk_users_has_business_business1_idx` (`business_id` ASC),
  INDEX `fk_users_has_business_users_idx` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_has_business_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `auditoria10`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_business_business1`
    FOREIGN KEY (`business_id`)
    REFERENCES `auditoria10`.`business` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auditoria10`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria10`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `aka` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `user_id` INT NOT NULL,
  `business_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_departments_business1_idx` (`business_id` ASC),
  INDEX `fk_departments_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_departments_business1`
    FOREIGN KEY (`business_id`)
    REFERENCES `auditoria10`.`business` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `auditoria10`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auditoria10`.`audits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria10`.`audits` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(100) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auditoria10`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria10`.`questions` (
  `id` INT NOT NULL,
  `question` VARCHAR(255) NOT NULL,
  `type` VARCHAR(45) NOT NULL DEFAULT 'optinal',
  `opc1` VARCHAR(100) NULL,
  `opc2` VARCHAR(100) NULL,
  `opc3` VARCHAR(100) NULL,
  `correct` VARCHAR(100) NULL,
  `comment` VARCHAR(255) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `audit_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_audits1_idx` (`audit_id` ASC),
  CONSTRAINT `fk_questions_audits1`
    FOREIGN KEY (`audit_id`)
    REFERENCES `auditoria10`.`audits` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auditoria10`.`audits_has_departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria10`.`audits_has_departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `audit_id` INT NOT NULL,
  `department_id` INT NOT NULL,
  `business_id` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  INDEX `fk_audits_has_departments_departments1_idx` (`department_id` ASC),
  INDEX `fk_audits_has_departments_audits1_idx` (`audit_id` ASC),
  INDEX `fk_audits_has_departments_business1_idx` (`business_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_audits_has_departments_audits1`
    FOREIGN KEY (`audit_id`)
    REFERENCES `auditoria10`.`audits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audits_has_departments_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `auditoria10`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audits_has_departments_business1`
    FOREIGN KEY (`business_id`)
    REFERENCES `auditoria10`.`business` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
